# docker-compose.yml
version: "3"
services:
  redis:
    image: redis
    container_name: redis-store
    expose:
      - 6379
    volumes:
      # Doesn't technically need to be a named volume
      - red_data:/data

  app:
    build: .
    volumes:
      - .:/var/www/app
      # expose a named volume that works because installing
      # and then mounting will hide that folder, so we need to explicitly
      # show it again
      # note that when reinstalling modules, we need to remove this volume
      - fe_modules:/var/www/app/node_modules
    ports:
      - 3000:3000
    links:
      - redis
    environment:
      # Change to production to reproduce prod issues
      - NODE_ENV=development
      # Defines what port to use for development
      - PORT=3000
      # Since this is linked to the redis contnainer, we can do a DNS lookup by
      # name.
      - REDIS_URL=redis://redis-store:6379
      # MTD API key used in the Express server, pulled as an environment variable
      - CUMTD_API_KEY=$CUMTD_API_KEY
    command:
      sh -c 'npm run start:dev'

# explicitly defines the volumes so that docker-compose down -v will destroy them
volumes:
  red_data:
  fe_modules:
